.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TWEETR" "1" "November 2016" "tweetr developers" ""
.
.SH "NAME"
\fBtweetr\fR \- Self\-hosted automatic tweet posting software
.
.SH "SYNOPSIS"
\fBtweetr\fR \fIOPTIONS\fR <SUBMODULE> [SUBMODULE_OPTIONS]
.
.SH "DESCRIPTION"
tweetr is a platform that allows you to create and queue tweets to be shared when YOU want\. You create content when you have time and then use FOSS and NOT pay whatever\-ridiculous amount of $$$ for posting them automatically\.
.
.P
In other words this is self\-hosted automatic tweet posting software\.
.
.P
See the subcommands for more information:
.
.IP "\(bu" 4
tweetr\-init(1) \- authorising the application
.
.IP "\(bu" 4
tweetr\-add\-user(1) \- adding and authorising users
.
.IP "\(bu" 4
tweetr\-queue\-tweet(1) \- adding tweets to the queue
.
.IP "\(bu" 4
tweetr\-start\-daemon(1) \- start the tweet\-posting daemon
.
.IP "" 0
.
.SH "OPTIONS"
\-c \-\-config\-dir <\fIconfig_dir\fR>
.
.IP "" 4
.
.nf

Directory with the configuration\.

The configuration directory contains all of tweetr\'s data\.

Default: $HOME/\.tweetr
.
.fi
.
.IP "" 0
.
.SH "EXAMPLES"
See the per\-subcommand examples page
.
.SH "AUTHOR"
Written by nabijaczleweli <\fInabijaczleweli@gmail\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/nabijaczleweli/tweetr/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/nabijaczleweli/tweetr\fR>
